### ISSUE TITLE
Screenshot requests photo library

### ISSUE THREAD

**Issue by lukeswitz** [RelistenNet/relisten-ios#172]
When a screenshot is taken on iOS 13, privacy dialogues appear informing me Relisten wants to access my photos. 

What plist entry and why does this code want direct access to the photo library? Seems like shady framework activity.

**Comment by alecgorge** [comment]
This comes from: https://github.com/Lickability/PinpointKit

We use the photo library to access the screenshot as part of our bug reporting so that people can annotate a screenshot and quickly have an email composed including all the relevant information.

Pinpoint is implemented to run all bug reporting over email and not send any information to 3rd parties. Before implementing PinpointKit, we often received screenshots from people in emails and this has helped streamline the process.

**Comment by lukeswitz** [comment]
TestFlight now offers this to all users. Removing the third party lib would be recommended. The app is not beta, correct?

**Comment by alecgorge** [comment]
My understanding is that the non-beta release of iOS 13 will not provide any built-in functionality for reporting bugs to developers.

This app has a beta version on TestFlight and a non-beta version on App Store.

**Comment by lukeswitz** [comment]
Per the Apple TestFlight docs: https://testflight.apple.com/join/MHHbkKaM 
> If your device is running iOS 13 beta, you can send feedback through the TestFlight app or directly from the beta app by taking a screenshot, and you can report a crash after it occurs. If you were invited to test an app with a public link, you can choose not to provide your email address or other personal information to the developer. Apple will also receive all feedback you submit and will be able to tie it to your Apple ID.

**Comment by lukeswitz** [comment]
Working great for us for months now. Cheers
