### ISSUE TITLE
Feature Request: State restoration

### ISSUE THREAD

**Issue by lukeswitz** [RelistenNet/relisten-ios#186]
What would the proper VC creation sequence be to achieve this? I can store the currentTrack data to parse as demonstrated in AppDelegate, but that schema doesn’t hold true for da Phish. 

Cheers & thanks

**Comment by lukeswitz** [comment]
closing, stale request

**Comment by farktronix** [comment]
This is something I've wanted in Relisten for a while. I have a branch where I started working on things, but then I found out that the state restoration story from Apple has changed. It looks like we want to switch to using `UIScene` and `NSUserActivity` and the system should take care of most of this for us. 

Switching to `UIScene` is also necessary for the latest CarPlay API  (#193), so that's something we'll need to before the old API is completely removed.

My memory is a bit fuzzy about where I left the state restoration work, but I remember that untangling the setup of AGAudioPlayer was one of the big parts. There's probably a fork in that repository with some work in progress that would still apply in the new world of `NSUserActivity`

**Comment by lukeswitz** [comment]
Thanks for the update on that, same thoughts. I've got the session to resume playing; Updating the UI to display the show is difficult but possible with what's there now I think. I'll enjoy giving it another try the hard way to learn the codebase a bit better. It took Apple Music until this year to get it right, so I'm not rushing it 😉
