### ISSUE TITLE
New persistence model

### ISSUE THREAD

**Issue by alecgorge** [RelistenNet/relisten-ios#43]
**Note**: this is quite rough and thought of late a night. This will require revisions:

# Relisten Persistence Model

All objects eligble for persistence have a `uuid` property.

## Is there a way that we can make persistence generic? How much storage is too much storage?

Objects with a `uuid` property vary in size. Some are consistent and small, like an `Artist`. Some objects can be large or small—such as `ShowWithSources`. The number of sources within the show or the corresponding descriptions can vary wildly from show to show—even within the same artist.

However, in theory, this is not a problem. Even a very large show with many sources isn’t completely unwieldy since the largest variable (reviews) is behind a separate API request now.

What we are really talking about is a difference between a couple hundred bytes and a couple kilobytes. Does this make a substantial difference on a modern iPhone? Let’s do the math, Fermi estimation style:

A true fan of a band might have 100 shows favorited. A truly rediculous show like Grateful Dead’s 5/8/1978 is a 281 KiB raw JSON response, but for a [Fermi estimation](https://en.wikipedia.org/wiki/Fermi_problem) let’s call it 200 KiB of resident memory. This means a wild fan of a band would need `200 KiB * 100 = 20,000 KiB = 20 MiB` of memory to hold all of their favorite shows within instant reach.

To be frank, 20 MiB isn’t a ton of memory and it may be premature optimization to break things down further/smaller than that. Even if we held twice as many objects in memory—which is more shows than many bands have played—we are still safely in a range where even a power-user on paltry iPhone 5S with 1GiB of RAM would be happy. We can’t give up 20 MiB here and 20 MiB there and come out with an acceptable memory usage (despite being ill-defined) but cutting out Firebase completely gives us a chunk of memory back (exact amount unknown).

**Summary**: Just hold all the shows in memory, but disk backed for persistence—it is easier and doesn’t enough memory to be even a minor issue.

## Okay, so we are holding all the shows in memory with a disk backing...how does that actually happen?

Siesta provides a really cool [pipeline stage called `cleanup`](https://bustoutsolutions.github.io/siesta/guide/pipeline/#pipeline-stages) that happens after the JSON response has been parsed into models. We can hook into this stage of the pipeline only on routes that return “persistent” models (ones with a `uuid`) using [`configure(whenURLMatches:requestMethods:description:configurer:)`](https://bustoutsolutions.github.io/siesta/api/Classes/Service.html#/s:6Siesta7ServiceC9configureySb10Foundation3URLVc14whenURLMatches_SayAA13RequestMethodOGSg14requestMethodsSSSg11descriptionyAA13ConfigurationVzc10configurertF).

We can use this to automatically store any `ShowWithSources` into different disk backed caches with 50 MiB automatically held in memory using `Cache`.

We can write to the cache anytime we receive a response and read from it whenever we want. Then, to maintain a “favorites” list we just have to store a list of `uuid`s and hydrate that from the cache whenever we need to access it. In general, the favorited shows should stay in memory and be quick to access. In the worst case, we need to go to the SSD and fetch it.

Because we do not sync, something can only be in favorites if it has been accessed on that device and we do not need to worry about cache misses which fetching the list of favorites. Of course, it is prudent to still handle (aka skip that show) this scenario despite it being “impossible” like so many programming bugs.

We should **not** hold an array of all the shows in memory that gets invalidated any time a show is favorited/un-favorited. This would double memory usage for no real benefit. We can assemble the whole list of shows from only the `uuid`s with very little overhead despite it feeling “wrong”. It might not be the *most* optimal, but it is great for our purposes because:

1. It is easy to reason about
2. This leads to less bugs
3. This leads to less maintence

Yay open source.

----------------

### Data Stores

* Cache for all offline data
	* Main holds  `ShowWithSources` entires with a key of `show_uuid`
	* Has a special entry called `__tracks$$` that holds a `[String: (show_uuid: String, source_uuid: String)]` mapping. This is held in memory manually and is persisted on every mutation.
	* Has a special entry called `__sources$$` that holds a `[String: String]` mapping from source UUIDs to show UUIDs
	* Has a special entry called `__favoriteShows$$` that holds a `[FavoriteShow]`
	* Has a special entry called `__favoriteSources$$` that holds a `[FavoriteSource]`
	* Has a special entry called `__favoriteTracks$$` that holds a `[FavoriteTrack]`
	* Has a special entry called `__playbackQueue$$` that holds a `PlaybackResortation` for restoring playback on launch

### Models

```
struct PlaybackRestoration {
	public let queue: [UUID] = [] // track UUIDs
	public let active: UUID? = nil // active track UUID
	public let playbackPosition: TimeInterval? = nil // position in active track
}

struct FavoriteShow {
	public let show_uuid: UUID
	public let created_at: Date
}

struct FavoriteSource {
	public let source_uuid: UUID
	public let created_at: Date
}

struct FavoriteTrack {
	public let track_uuid: UUID
	public let created_at: Date
}

struct SourceFullInShowWithSources {
	public let show: ShowWithSources
	public let source: SourceFull
}

struct SourceTrackInSourceFullInShowWithSources {
	public let show: ShowWithSources
	public let source: SourceFull
	public let track: SourceTrack
}
```

### Methods

* `show(byUUID: UUID) -> ShowWithSources`
	* Simple, straight backing-cache lookup
*  `source(byUUID: UUID) -> SourceFullInShowWithSources`
	* Uses `__sources$$` to lookup the show `uuid`
	* Uses the backing cache to pull full information
	* Finds the matching source within
*  `show(forSourceUUID uuid: UUID) -> ShowWithSources `
	* `source(byUUID: uuid).show`
*  `show(byTrackUUID uuid: UUID) -> ShowWithSources`
	* `track(byUUID: uuid).show`
*  `source(byTrackUUID uuid: UUID) -> SourceFull`
	* `track(byUUID: uuid).source`
* `track(byUUID uuid: UUID) -> SourceTrackInSourceFullInShowWithSources`
	* Uses `__tracks$$` to find the show `uuid`
	* Uses the backing cache to pull full information
	* Filters to find the matching source
*  `save(show: ShowWithSources)`
	* Adds an entry to `__tracks$$` for every track in every set
	* Adds an entry to `__sources$$` for every source
* `addFavorite(show: Show, in show: ShowWithSources)`
	* Adds an entry to `__favoriteShows$$`
	* calls `save(show: show)`
* `addFavorite(source: Source, in show: ShowWithSources)`
	* Adds an entry to `__favoriteSources$$`
	* calls `save(show: show)`
* `addFavorite(track: SourceTrack, in show: ShowWithSources)`
	* Adds an entry to `__favoriteTracks$$`
	* calls `save(show: show)`
* `removeFavorite(_ uuid: UUID) -> Bool`
	* Removes from any of the favorite arrays, stopping on the first successful removal
* `savePlaybackRestorationInformation(_ info: PlaybackRestoration)`
* `public let favoriteShows: Observable<[ShowWithSources]>`
* `public let favoriteSources: Observable<[SourceFullInShowWithSources]>`
* `favoriteSourcesIncludingIndirect() -> [SourceFullInShowWithSources]`
	* Any direct favorites + any sources from favorite shows
* `public let favoriteTracks: Observable<[SourceTrackInSourceFullInShowWithSources]>`
* `favoriteTracksIncludingIndirect() -> [SourceTrackInSourceFullInShowWithSources]`
	* Any direct favorites + any tracks from favorite sources + any tracks from favorite show

## Migration to user based API in future

Easy here because the special keys are just cached version of things fetched on the server. Updated before any change—like `git pull --rebase origin master`—then change is applied. Also updated on any app open. No offline support for modifying favorites.

**Comment by farktronix** [comment]
I feel like I'm coming from a completely different side of the same world here. At Apple we were under constant pressure to keep daemon memory use and disk writes down. 20MB was super high, and there's a real cost to writing unnecessarily to the SSD, since it physically burns out the chip. There's a big difference between a daemon that runs almost all the time and an app that people only use occasionally, but I'm still stingy with memory use 😁 

The math checks out though, and keeping everything in memory (backed by a disk cache) probably isn't awful. It'd be easier to start with this and then optimize from there. 
My biggest concern is the CPU price of figuring out things like how many favorited/downloaded tracks there are for an artist by scanning in-memory objects versus doing a quick lookup on an indexed sqlite table. We can profile that when the time comes though.

### Offline Mode
I like the `cleanup` hook into Siesta. I think it would also be good to always persist the list of Artists, since that rarely changes. That would also allow Relisten to launch to its main screen even while offline, and you could then drill down into an artist to see your favorites/downloads for that artist rather than seeing everything in one big list.

If you try to drill into anything that depends on the API (years/songs/on this date/etc) then you'll get a screen with an offline error message. You can go into your list of downloads and play those songs though, or you can view your favorites since that information is all cached.

The big challenge here is deciding when to use the offline cache data and when to use the live data, and seamlessly switching between the two. My idea for that is to use the offline data to immediately populate a view (for artists/favorites/downloads), but then make a Siesta request for the real data (for the artist list and source view). If the real data shows up then it you can reload the data in the view with the latest and greatest from the API.


### Notes on the implementation
Do downloaded tracks fit into this cache, or are they in a separate cache? I'd like to combine the downloaded track info and the download queue by making them the same cache with a flag for the state (queued/downloading/downloaded). In the longer term I'd like to add another state for cached tracks that were streamed.

A note on naming: I've found that naming dictionaries with both of the items they contain is very helpful. `__tracksToShowAndSource` and `__sourceToShow` make it a bit easier when I'm writing code using them because I immediately know what value to expect out of the dictionary.

I'm not sure `favoriteShows` is necessary- isn't that covered by `favoriteSources`? The favorite button is in the source view, and when favorite sources are displayed to the user they're displayed as shows.

There should also be a `__favoriteArtists$$ -> [Artist]` for favoriting artists on the main screen.

`PlaybackRestoration` should have a `playbackState` so you don't start automatically playing a song that was paused. You might also want flags for whether shuffle and repeat were enabled.

What about doing a class hierarchy for favorites and just having one array?

```
class FavoriteItem {
    public let created_at: Date
}

class FavoriteArtist : FavoriteItem {
    public let artist_uuid: UUID
}

class FavoriteSource : FavoriteItem {
    public let source_uuid: UUID
}

class FavoriteTrack : FavoriteItem {
    public let track_uuid: UUID
}
```

Then you just have `___favorites$$ -> [FavoriteItem]` in the cache. Maybe that just looks cleaner in the definition but it's messier when it comes to fetching specific items out of the cache. I'm not too familiar with how to deal with this in Swift.
